spring.application.name=tienda-backend
spring.datasource.url=jdbc:postgresql://ep-lingering-cherry-ac1dypf7-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_W7MOfGz3lZsk
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true